# Generated by Django 5.2.6 on 2025-12-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='face_recognition_success',
        ),
    ]
