# Generated by Django 5.2.6 on 2025-12-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_attendance_face_recognition_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='photo',
        ),
    ]