# Generated by Django 5.2.6 on 2025-12-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_break_ot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ot',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ot',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Break',
        ),
        migrations.DeleteModel(
            name='OT',
        ),
    ]
