# Generated by Django 5.2.7 on 2025-12-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_break_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='location_type',
            field=models.CharField(choices=[('office', 'Office'), ('work', 'Work From Home')], default='office', max_length=10),
        ),
    ]
