# Generated by Django 5.2.6 on 2026-02-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_attendance_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
