# Generated by Django 5.2.6 on 2025-12-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_create_shift_model'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS accounts_shift CASCADE;"),
    ]