# Generated by Django 5.2.6 on 2025-12-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_auto_20251202_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('emp_name', models.CharField(max_length=255)),
                ('manager_name', models.CharField(max_length=255)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=10)),
                ('emp_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shifts', to='accounts.user')),
                ('manager_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_shifts', to='accounts.user')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('emp_email', 'date', 'time'), name='unique_employee_shift'),
        ),
    ]